<a href="https://colab.research.google.com/github/mohitpreet9435-gif/northstar-operational-data-overview/blob/main/03_Dataset_Overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Required Libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Load Dataset Files from GitHub

In [3]:
# Import datasets from GitHub

app_events = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/app_events.csv")

complaints = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/complaints.csv")

customers = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/customers.csv")

data_dictionary = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/data_dictionary.csv")

deliveries = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/deliveries.csv")

drivers = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/drivers.csv")

hubs = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/hubs.csv")

incidents = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/incidents.csv")

orders = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/orders.csv")

vehicles = pd.read_csv("https://raw.githubusercontent.com/mohitpreet9435-gif/Dataset/main/vehicles.csv")

print(vehicles)

    vehicle_id vehicle_type assigned_zone      commission_date  \
0         V001           EV         North  2024-12-28 23:48:00
1         V002           EV       AIRPORT  2024-04-21 16:14:00
2         V003     CargoVan         north  2025-11-24 23:59:00
3         V004       Hybrid     RiverSide  2024-06-07 13:21:00
4         V005     CargoVan          West  2025-11-15 11:08:00
..         ...          ...           ...                  ...
115       V116       Diesel          EAST  2025-04-23 07:10:00
116       V117       Hybrid         SOUTH  2025-01-11 11:13:00
117       V118       Diesel     Riverside  2025-02-18 12:40:00
118       V119           EV     RiverSide  2025-08-17 06:19:00
119       V120           EV       CENTRAL  2025-05-02 16:13:00

     battery_health_pct  odometer_km maintenance_status telematics_version
0                  71.8        56928             Active               v2.2
1                  67.9       159368           InRepair               v2.2
2                  91.7       219359             Active               v2.1
3                   NaN        36310             Active               v2.2
4                  58.6       146638             Active               v2.2
..                  ...          ...                ...                ...
115                62.7        71822             Active               v2.1
116                65.5       163683          Scheduled               v2.2
117                78.0       145165             Active               v2.1
118                67.6       215407           InRepair               v2.1
119                73.6       192246             Active               v2.0

[120 rows x 8 columns]

# Display Dataset Preview

In [4]:
# Preview datasets

print("Customers Dataset")
display(customers.head())

print("Deliveries Dataset")
display(deliveries.head())

print("Orders Dataset")
display(orders.head())

Customers Dataset

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

Deliveries Dataset

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

Orders Dataset

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

#  Display Dataset Information

In [5]:
# Dataset structure and information

print("Customers Dataset Info")
customers.info()

print("\nDeliveries Dataset Info")
deliveries.info()

print("\nOrders Dataset Info")
orders.info()

Customers Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB

Deliveries Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB

Orders Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB

# Check Missing Values

In [6]:
# Missing values check

print("Missing Values in Customers Dataset")
print(customers.isnull().sum())

print("\nMissing Values in Deliveries Dataset")
print(deliveries.isnull().sum())

print("\nMissing Values in Orders Dataset")
print(orders.isnull().sum())

Missing Values in Customers Dataset
customer_id              0
age                      0
home_zone                0
customer_type            0
signup_date              0
loyalty_score           20
app_engagement_score     0
preferred_channel       13
account_status           0
dtype: int64

Missing Values in Deliveries Dataset
delivery_id                       0
order_id                          0
driver_id                         0
vehicle_id                        0
hub_id                            0
dispatch_time                     0
delivery_completed_at            19
delivery_status                   0
route_distance_km                 0
manual_route_override_count       0
proof_of_completion_missing       0
customer_rating_post_delivery    14
fuel_or_charge_cost               0
dtype: int64

Missing Values in Orders Dataset
order_id                  0
customer_id               0
service_type              0
order_created_at          0
promised_window_hours     0
pickup_zone               0
dropoff_zone              0
priority_level            0
order_value               0
booking_channel          25
special_handling_flag     0
dtype: int64

# Dataset Dimensions

In [7]:
# Dataset dimensions

print("Customers Shape:", customers.shape)
print("Deliveries Shape:", deliveries.shape)
print("Orders Shape:", orders.shape)
print("Complaints Shape:", complaints.shape)
print("App Events Shape:", app_events.shape)

Customers Shape: (650, 9)
Deliveries Shape: (950, 13)
Orders Shape: (1250, 11)
Complaints Shape: (320, 10)
App Events Shape: (640, 10)

# Statistical Summary

In [8]:
# Statistical summary

display(customers.describe())

display(deliveries.describe())

              age  loyalty_score  app_engagement_score
count  650.000000     630.000000            650.000000
mean    46.738462      59.690635             58.132308
std     17.449179      16.124674             18.918154
min     18.000000      13.100000              1.000000
25%     32.000000      49.000000             45.375000
50%     46.000000      59.600000             59.000000
75%     62.000000      70.450000             72.000000
max     78.000000      99.000000            100.000000

,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
count,950.000000,950.000000,950.000000,936.000000,950.000000
mean,13.909316,0.969474,0.072632,3.864679,12.841295
std,7.477907,1.093189,0.259667,0.894420,4.336468
min,1.200000,0.000000,0.000000,1.000000,2.500000
25%,9.135000,0.000000,0.000000,3.360000,9.925000
50%,12.840000,1.000000,0.000000,4.040000,12.645000
75%,16.835000,2.000000,0.000000,4.550000,15.697500
max,41.940000,7.000000,1.000000,5.000000,29.430000